version: '3.8'

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn server.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./:/code/server
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
